{"trial_id": "02", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "conv_0", "default": 16, "conditions": [], "min_value": 8, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_0", "default": 0.5, "conditions": [], "min_value": 0.1, "max_value": 0.8, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "conv_1", "default": 32, "conditions": [], "min_value": 16, "max_value": 128, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_1", "default": 0.5, "conditions": [], "min_value": 0.1, "max_value": 0.8, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_0", "default": 128, "conditions": [], "min_value": 32, "max_value": 256, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_2", "default": 0.5, "conditions": [], "min_value": 0.1, "max_value": 0.8, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_1", "default": 64, "conditions": [], "min_value": 16, "max_value": 128, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_3", "default": 0.5, "conditions": [], "min_value": 0.1, "max_value": 0.8, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "min_value": 1e-05, "max_value": 0.001, "step": null, "sampling": "log"}}], "values": {"conv_0": 64, "dropout_0": 0.8, "conv_1": 128, "dropout_1": 0.4, "dense_0": 208, "dropout_2": 0.6, "dense_1": 88, "dropout_3": 0.6, "learning_rate": 1.4274462262172177e-05}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_836/1081413896.py\", line 2, in <module>\n\n  File \"/mnt/c/Users/luiza/Desktop/Mestrado/Trabalho/Trainer/Trainer.py\", line 30, in train\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 318, in fit\n\n  File \"/home/luiz/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 121, in one_step_on_iterator\n\nOut of memory while trying to allocate 1005909640 bytes.\nBufferAssignment OOM Debugging.\nBufferAssignment stats:\n             parameter allocation:   92.92MiB\n              constant allocation:         4B\n        maybe_live_out allocation:   87.29MiB\n     preallocated temp allocation:  959.31MiB\n  preallocated temp fragmentation:       188B (0.00%)\n                 total allocation:    1.03GiB\n              total fragmentation:     7.2KiB (0.00%)\nPeak buffers:\n\tBuffer 1:\n\t\tSize: 319.75MiB\n\t\tOperator: op_type=\"MaxPoolGrad\" op_name=\"gradient_tape/sequential_1/max_pooling2d_1/MaxPool2d/MaxPoolGrad\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: select-and-scatter\n\t\tShape: f32[32,2558,16,64]\n\t\t==========================\n\n\tBuffer 2:\n\t\tSize: 319.75MiB\n\t\tOperator: op_type=\"Conv2D\" op_name=\"sequential_1/conv2d_1/convolution\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: custom-call\n\t\tShape: f32[32,64,2558,16]\n\t\t==========================\n\n\tBuffer 3:\n\t\tSize: 319.75MiB\n\t\tOperator: op_type=\"ReluGrad\" op_name=\"gradient_tape/sequential_1/conv2d_1/ReluGrad\"\n\t\tXLA Label: fusion\n\t\tShape: f32[32,64,2558,16]\n\t\t==========================\n\n\tBuffer 4:\n\t\tSize: 28.74MiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_4\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[36224,208]\n\t\t==========================\n\n\tBuffer 5:\n\t\tSize: 28.74MiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_4\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[36224,208]\n\t\t==========================\n\n\tBuffer 6:\n\t\tSize: 28.74MiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_4\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[36224,208]\n\t\t==========================\n\n\tBuffer 7:\n\t\tSize: 5.62MiB\n\t\tOperator: op_name=\"XLA_Args\"\n\t\tEntry Parameter Subshape: f32[32,2560,18,1]\n\t\t==========================\n\n\tBuffer 8:\n\t\tSize: 288.0KiB\n\t\tOperator: op_name=\"XLA_Args\"\n\t\tEntry Parameter Subshape: f32[3,3,64,128]\n\t\t==========================\n\n\tBuffer 9:\n\t\tSize: 288.0KiB\n\t\tOperator: op_name=\"XLA_Args\"\n\t\tEntry Parameter Subshape: f32[3,3,64,128]\n\t\t==========================\n\n\tBuffer 10:\n\t\tSize: 288.0KiB\n\t\tOperator: op_name=\"XLA_Args\"\n\t\tEntry Parameter Subshape: f32[3,3,64,128]\n\t\t==========================\n\n\tBuffer 11:\n\t\tSize: 71.5KiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_6\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[18304]\n\t\t==========================\n\n\tBuffer 12:\n\t\tSize: 71.5KiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_6\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[18304]\n\t\t==========================\n\n\tBuffer 13:\n\t\tSize: 71.5KiB\n\t\tOperator: op_type=\"AssignSubVariableOp\" op_name=\"adam/AssignSubVariableOp_6\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[18304]\n\t\t==========================\n\n\tBuffer 14:\n\t\tSize: 26.0KiB\n\t\tOperator: op_type=\"SelectV2\" op_name=\"sequential_1/dropout_2_1/stateless_dropout/SelectV2\" source_file=\"/home/luiz/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177\n\t\tXLA Label: fusion\n\t\tShape: f32[32,208]\n\t\t==========================\n\n\tBuffer 15:\n\t\tSize: 16.0KiB\n\t\tXLA Label: fusion\n\t\tShape: f32[32,128]\n\t\t==========================\n\n\n\t [[{{node StatefulPartitionedCall}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_one_step_on_iterator_1839662]\n"}